env:
  browser: true

parserOptions:
  ecmaVersion: 6

extends:
  - eslint:recommended

rules:
  no-console: warn
  no-unused-vars: [error, { argsIgnorePattern: "^_" }]
  no-useless-escape: warn  # TODO: remove (so this is an error)

overrides:
  # Client:
  - files: [ "routes/*.js", "static/**/*.js" ]
    globals:
      $: false
      ABE_API_URI: false
      SUBMIT_URL: true
      db: false
      showdown: false
      # defined and used in admin.js:
      tableColumns: true
      # defined in server.js:
      io: true
      # defined and used in board_carousel:
      $activeItem: true
      $carousel: true
      carouselSelector: true
      # defined in vendor files:
      Cookies: false
      Dropzone: false
    rules:
      # FIXME: remove these exceptions, to turn them back into errors
      no-undef: warn
      no-unused-vars: warn
      no-redeclare: warn
  # Server:
  - files: [ "server.js", "models/*.js", "routes/*.js", "scripts/*.js" ]
    env:
      browser: false
      node: true
    globals:
      Promise: false
      module: false
      require: false
    rules:
      no-console: off
