env:
  browser: true

parserOptions:
  ecmaVersion: 6

extends:
  - eslint:recommended

# see https://eslint.org/docs/user-guide/configuring#specifying-globals
globals:
  db: false

rules:
  no-console: warn
  no-unused-vars: [error, { argsIgnorePattern: "^_" }]
  no-useless-escape: warn # TODO: remove (so this is an error)

# Server-side:
overrides:
  files: [ "*.js", "models/*.js", "routes/*.js", "scripts/*.js" ]
  env:
    browser: false
    node: true
  globals:
    Promise: false
    module: false
    require: false
  rules:
    no-console: off
